[package]
name = "_"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.64"
speedy = "0.8.6"
wasm-bindgen = "0.2.87"

[profile.release]
opt-level = 's'
lto = true
