[package]
name = "_"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
intbin = "0.1.2"
js-sys = "0.3.65"
wasm-bindgen = "0.2.88"

[profile.release]
opt-level = 's'
lto = true
